const suits=[{s:'♠',c:'black'},{s:'♥',c:'red'},{s:'♦',c:'red'},{s:'♣',c:'black'}],faces={1:{name:'TIGER WOODS',img:'assets/tiger-woods.jpg'},11:{name:'MAC MILLER',img:'assets/mac-miller.jpg'},12:{name:'TANA MONGEAU',img:'assets/tana-mongeau.png'},13:{name:'FLEA',img:'assets/flea-live.jpg'}};
let stock=[],waste=[],foundations=[[],[],[],[]],tableau=[[],[],[],[],[],[],[]],selected=null,moves=0,initialDeck=[],history=[],autoFinishing=false,autoFinishPaused=false,autoTimer,lastClick={id:null,time:0};
const $=s=>document.querySelector(s),tableauEl=$('#tableau'),foundationEl=$('#foundations');
function deck(){return suits.flatMap((s,si)=>Array.from({length:13},(_,i)=>({suit:si,rank:i+1,up:false,id:`${si}-${i+1}`})))}
function shuffle(a){for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function deal(cards,animate=false){stock=cards.map(c=>({...c}));waste=[];foundations=[[],[],[],[]];tableau=[[],[],[],[],[],[],[]];for(let col=0;col<7;col++)for(let row=0;row<=col;row++){let c=stock.pop();c.up=row===col;tableau[col].push(c)}selected=null;moves=0;render(null,animate)}
function solvableDeck(){let counts=[1,1,1,1];for(let i=0;i<24;i++){let choices=[0,1,2,3].filter(s=>counts[s]<13),s=choices[Math.floor(Math.random()*choices.length)];counts[s]++}let tableauOrder=[],next=[1,1,1,1];while(tableauOrder.length<28){let choices=[0,1,2,3].filter(s=>next[s]<=counts[s]),s=choices[Math.floor(Math.random()*choices.length)],rank=next[s]++;tableauOrder.push({suit:s,rank,up:false,id:`${s}-${rank}`})}let sizes=shuffle([1,2,3,4,5,6,7]),cols=Array.from({length:7},()=>[]),offset=0;sizes.forEach(size=>{let ci=size-1,chunk=tableauOrder.slice(offset,offset+size);cols[ci]=chunk.reverse();offset+=size});let drawOrder=[];while(drawOrder.length<24){let choices=[0,1,2,3].filter(s=>next[s]<=13),s=choices[Math.floor(Math.random()*choices.length)],rank=next[s]++;drawOrder.push({suit:s,rank,up:false,id:`${s}-${rank}`})}return [...drawOrder.reverse(),...cols.flat().reverse()]}
function cancelAutoFinish(){autoFinishing=false;autoFinishPaused=false;clearTimeout(autoTimer);$('#gameHint').textContent='EVERY DEAL IS SOLVABLE · DRAG OR CLICK, THEN DESTINATION · ESC CANCELS · DOUBLE-CLICK AUTO-MOVES'}
function newDeal(){cancelAutoFinish();$('#win').hidden=true;history=[];initialDeck=solvableDeck();deal(initialDeck,true)}function restart(){cancelAutoFinish();$('#win').hidden=true;history=[];deal(initialDeck,true)}
function label(r){return r===1?'A':r===11?'J':r===12?'Q':r===13?'K':r}
function beginDrag(type,index,cardIndex,e){if(type==='waste')selected={type,index:0,cardIndex:waste.length-1,cards:[waste.at(-1)]};else if(type==='foundation')selected={type,index,cardIndex,cards:[foundations[index].at(-1)]};else if(type==='tableau'){let card=tableau[index][cardIndex];if(!card?.up)return e.preventDefault();selected={type,index,cardIndex,cards:tableau[index].slice(cardIndex)}}else return e.preventDefault();e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',selected.cards[0].id)}
function allowDrop(e){e.preventDefault();e.dataTransfer.dropEffect='move'}
function cardEl(c,source,index,cardIndex){let el=document.createElement('div');el.className=`card ${c.up?'':'back'} ${suits[c.suit].c==='red'?'red':''}`;el.dataset.id=c.id;if(selected?.cards?.some(x=>x.id===c.id))el.classList.add('selected');if(c.up){let f=faces[c.rank];el.innerHTML=`<span class="rank">${label(c.rank)}<br>${suits[c.suit].s}</span><span class="rank bottom">${label(c.rank)}<br>${suits[c.suit].s}</span>${f?`<img class="portrait" draggable="false" src="${f.img}" alt="${f.name}"><span class="name">${f.name}</span>`:`<span class="pip">${suits[c.suit].s}</span>`}`;el.draggable=source!=='stock';el.ondragstart=e=>beginDrag(source,index,cardIndex,e);el.ondragend=()=>{if(selected){selected=null;render()}};el.onclick=e=>{e.stopPropagation();let now=performance.now();if(lastClick.id===c.id&&now-lastClick.time<450){lastClick={id:null,time:0};return autoMove(source,index,cardIndex)}lastClick={id:c.id,time:now};if(selected?.cards?.some(x=>x.id===c.id)){selected=null;return render()}if(selected){if(source==='tableau')return moveToTableau(index);if(source==='foundation')return moveToFoundation(index)}choose(source,index,cardIndex)};el.ondblclick=e=>e.preventDefault()}return el}
function capturePositions(){return Object.fromEntries([...document.querySelectorAll('.card[data-id]')].map(el=>[el.dataset.id,el.getBoundingClientRect()]))}
function animateCards(before,dealAnimation=false){let cards=[...document.querySelectorAll('.card[data-id]')];if(dealAnimation){let origin=$('#stock').getBoundingClientRect();cards.filter(el=>el.closest('#tableau')).forEach((el,i)=>{let end=el.getBoundingClientRect();el.animate([{transform:`translate(${origin.left-end.left}px,${origin.top-end.top}px)`,opacity:.25},{transform:'translate(0,0)',opacity:1}],{duration:320,delay:i*22,easing:'cubic-bezier(.2,.8,.2,1)',fill:'backwards'})});return}if(!before)return;cards.forEach(el=>{let start=before[el.dataset.id];if(!start)return;let end=el.getBoundingClientRect(),dx=start.left-end.left,dy=start.top-end.top;if(Math.abs(dx)>1||Math.abs(dy)>1)el.animate([{transform:`translate(${dx}px,${dy}px)`,zIndex:200},{transform:'translate(0,0)',zIndex:200}],{duration:280,easing:'cubic-bezier(.2,.8,.2,1)'})})}
function render(before=null,dealAnimation=false){tableauEl.innerHTML='';tableauEl.style.minHeight=`${Math.max(360,Math.max(...tableau.map(c=>c.length),1)*32+190)}px`;tableau.forEach((col,ci)=>{let pile=document.createElement('div');pile.className='column';pile.onclick=()=>moveToTableau(ci);pile.ondragover=allowDrop;pile.ondrop=e=>{e.preventDefault();moveToTableau(ci)};col.forEach((c,i)=>{let el=cardEl(c,'tableau',ci,i);el.style.top=`${i*32}px`;el.style.zIndex=i;pile.append(el)});tableauEl.append(pile)});let st=$('#stock');st.innerHTML='';st.dataset.label='↻';if(stock.length){let c=cardEl({...stock.at(-1),up:false},'stock',0,0);st.append(c)}st.onclick=draw;let wa=$('#waste');wa.innerHTML='';wa.dataset.label='WASTE';waste.slice(-3).forEach((c,i,a)=>{let el=cardEl(c,'waste',0,waste.length-a.length+i);el.style.left=`${i*5}px`;el.style.top=`${i*3}px`;el.style.zIndex=i;if(i<a.length-1){el.draggable=false;el.style.pointerEvents='none'}wa.append(el)});foundationEl.innerHTML='';foundations.forEach((f,i)=>{let p=document.createElement('div');p.className='pile';p.dataset.label=suits[i].s;p.onclick=()=>moveToFoundation(i);p.ondragover=allowDrop;p.ondrop=e=>{e.preventDefault();moveToFoundation(i)};if(f.length)p.append(cardEl(f.at(-1),'foundation',i,f.length-1));foundationEl.append(p)});$('#moves').textContent=`${moves} MOVE${moves===1?'':'S'}`;$('#undo').disabled=history.length===0;checkWin();animateCards(before,dealAnimation)}
function snapshot(){return{stock:stock.map(c=>({...c})),waste:waste.map(c=>({...c})),foundations:foundations.map(p=>p.map(c=>({...c}))),tableau:tableau.map(p=>p.map(c=>({...c}))),moves}}
function saveHistory(){history.push(snapshot());if(history.length>100)history.shift()}
function undo(){cancelAutoFinish();autoFinishPaused=true;if(!history.length)return;let before=capturePositions(),state=history.pop();stock=state.stock;waste=state.waste;foundations=state.foundations;tableau=state.tableau;moves=state.moves;selected=null;lastClick={id:null,time:0};$('#win').hidden=true;render(before)}
function draw(){autoFinishPaused=false;let before=capturePositions();saveHistory();selected=null;if(stock.length){let c=stock.pop();c.up=true;waste.push(c)}else{stock=waste.reverse().map(c=>({...c,up:false}));waste=[]}moves++;render(before)}
function choose(type,index,cardIndex){if(type==='stock')return draw();if(type==='foundation'){selected={type,index,cardIndex,cards:[foundations[index].at(-1)]};return render()}if(type==='waste'){selected={type,index:0,cardIndex:waste.length-1,cards:[waste.at(-1)]};return render()}let col=tableau[index],card=col[cardIndex];if(!card.up)return;selected={type,index,cardIndex,cards:col.slice(cardIndex)};render()}
function validTableau(card,target){if(!target)return card.rank===13;return target.up&&suits[card.suit].c!==suits[target.suit].c&&card.rank===target.rank-1}
function take(){if(!selected)return[];let cards;if(selected.type==='waste')cards=[waste.pop()];else if(selected.type==='foundation')cards=[foundations[selected.index].pop()];else cards=tableau[selected.index].splice(selected.cardIndex);return cards}
function reveal(ci){let c=tableau[ci]?.at(-1);if(c&&!c.up)c.up=true}
function moveToTableau(ci){if(!selected)return;let first=selected.cards[0],target=tableau[ci].at(-1);if(!validTableau(first,target))return;autoFinishPaused=false;let before=capturePositions();saveHistory();let from=selected.type==='tableau'?selected.index:null,cards=take();tableau[ci].push(...cards);if(from!==null)reveal(from);selected=null;moves++;render(before)}
function moveToFoundation(fi){if(!selected||selected.cards.length!==1)return;let c=selected.cards[0],top=foundations[fi].at(-1);if(c.suit!==fi||c.rank!==(top?top.rank+1:1))return;autoFinishPaused=false;let before=capturePositions();saveHistory();let from=selected.type==='tableau'?selected.index:null;foundations[fi].push(take()[0]);if(from!==null)reveal(from);selected=null;moves++;render(before)}
function autoMove(type,index,cardIndex){choose(type,index,cardIndex);if(!selected)return;let card=selected.cards[0];if(selected.cards.length===1){let top=foundations[card.suit].at(-1);if(card.rank===(top?top.rank+1:1))return moveToFoundation(card.suit)}let destination=tableau.findIndex((col,ci)=>!(type==='tableau'&&ci===index)&&validTableau(card,col.at(-1)));if(destination>=0)return moveToTableau(destination);selected=null;render()}
function readyToAutoFinish(){return !stock.length&&!waste.length&&tableau.every(col=>col.every(c=>c.up))&&tableau.some(col=>col.length)}
function autoFinishStep(){if(!autoFinishing||!readyToAutoFinish())return cancelAutoFinish();let ci=tableau.findIndex(col=>{let c=col.at(-1);return c&&c.rank===(foundations[c.suit].at(-1)?.rank||0)+1});if(ci<0)return cancelAutoFinish();let c=tableau[ci].at(-1);selected={type:'tableau',index:ci,cardIndex:tableau[ci].length-1,cards:[c]};moveToFoundation(c.suit);if(autoFinishing)autoTimer=setTimeout(autoFinishStep,190)}
function checkWin(){if(foundations.every(f=>f.length===13)){autoFinishing=false;clearTimeout(autoTimer);$('#winMoves').textContent=`Completed in ${moves} moves.`;$('#win').hidden=false;return}if(readyToAutoFinish()&&!autoFinishing&&!autoFinishPaused){autoFinishing=true;$('#gameHint').textContent='AUTO-FINISHING · ALL CARDS ARE FACE-UP AND THE WASTE IS EMPTY';autoTimer=setTimeout(autoFinishStep,240)}}
$('#newDeal').onclick=newDeal;$('#restart').onclick=restart;$('#undo').onclick=undo;$('#playAgain').onclick=()=>{$('#win').hidden=true;newDeal()};$('#creditsButton').onclick=()=>$('#credits').showModal();$('#credits .close').onclick=()=>$('#credits').close();
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&selected){selected=null;render()}});
$('#creditList').innerHTML=`<p><b>Mac Miller:</b> Nicolas Völcker, CC BY-SA 4.0.</p><p><b>Tana Mongeau:</b> Tanner Fox, CC BY 3.0.</p><p><b>Flea:</b> Clare Cridland, CC BY 2.0.</p><p><b>Tiger Woods:</b> Jim Epler, CC BY 2.0.</p><p>See ATTRIBUTION.md for source links and full license details.</p>`;
newDeal();
