const suits=[{s:'♠',c:'black'},{s:'♥',c:'red'},{s:'♦',c:'red'},{s:'♣',c:'black'}],faces={1:{name:'TIGER WOODS',img:'assets/tiger-woods.jpg'},11:{name:'MAC MILLER',img:'assets/mac-miller.jpg'},12:{name:'TANA MONGEAU',img:'assets/tana-mongeau.png'},13:{name:'FLEA',img:'assets/flea-live.jpg'}};
let stock=[],waste=[],foundations=[[],[],[],[]],tableau=[[],[],[],[],[],[],[]],selected=null,moves=0,initialDeck=[];
const $=s=>document.querySelector(s),tableauEl=$('#tableau'),foundationEl=$('#foundations');
function deck(){return suits.flatMap((s,si)=>Array.from({length:13},(_,i)=>({suit:si,rank:i+1,up:false,id:`${si}-${i+1}`})))}
function shuffle(a){for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function deal(cards){stock=cards.map(c=>({...c}));waste=[];foundations=[[],[],[],[]];tableau=[[],[],[],[],[],[],[]];for(let col=0;col<7;col++)for(let row=0;row<=col;row++){let c=stock.pop();c.up=row===col;tableau[col].push(c)}selected=null;moves=0;render()}
function newDeal(){initialDeck=shuffle(deck());deal(initialDeck)}function restart(){deal(initialDeck)}
function label(r){return r===1?'A':r===11?'J':r===12?'Q':r===13?'K':r}
function cardEl(c,source,index,cardIndex){let el=document.createElement('div');el.className=`card ${c.up?'':'back'} ${suits[c.suit].c==='red'?'red':''}`;el.dataset.id=c.id;if(selected?.cards?.some(x=>x.id===c.id))el.classList.add('selected');if(c.up){let f=faces[c.rank];el.innerHTML=`<span class="rank">${label(c.rank)}<br>${suits[c.suit].s}</span><span class="rank bottom">${label(c.rank)}<br>${suits[c.suit].s}</span>${f?`<img class="portrait" src="${f.img}" alt="${f.name}"><span class="name">${f.name}</span>`:`<span class="pip">${suits[c.suit].s}</span>`}`;el.onclick=e=>{e.stopPropagation();choose(source,index,cardIndex)};el.ondblclick=e=>{e.stopPropagation();autoFoundation(source,index,cardIndex)}}return el}
function render(){tableauEl.innerHTML='';tableau.forEach((col,ci)=>{let pile=document.createElement('div');pile.className='column';pile.onclick=()=>moveToTableau(ci);col.forEach((c,i)=>{let el=cardEl(c,'tableau',ci,i);el.style.top=`${i*32}px`;el.style.zIndex=i;pile.append(el)});tableauEl.append(pile)});let st=$('#stock');st.innerHTML='';st.dataset.label='↻';if(stock.length){let c=cardEl({...stock.at(-1),up:false},'stock',0,0);st.append(c)}st.onclick=draw;let wa=$('#waste');wa.innerHTML='';wa.dataset.label='WASTE';if(waste.length){let c=cardEl(waste.at(-1),'waste',0,waste.length-1);wa.append(c)}foundationEl.innerHTML='';foundations.forEach((f,i)=>{let p=document.createElement('div');p.className='pile';p.dataset.label=suits[i].s;p.onclick=()=>moveToFoundation(i);if(f.length)p.append(cardEl(f.at(-1),'foundation',i,f.length-1));foundationEl.append(p)});$('#moves').textContent=`${moves} MOVE${moves===1?'':'S'}`;checkWin()}
function draw(){selected=null;if(stock.length){let c=stock.pop();c.up=true;waste.push(c)}else{stock=waste.reverse().map(c=>({...c,up:false}));waste=[]}moves++;render()}
function choose(type,index,cardIndex){if(type==='stock')return draw();if(type==='foundation'){selected={type,index,cardIndex,cards:[foundations[index].at(-1)]};return render()}if(type==='waste'){selected={type,index:0,cardIndex:waste.length-1,cards:[waste.at(-1)]};return render()}let col=tableau[index],card=col[cardIndex];if(!card.up)return;selected={type,index,cardIndex,cards:col.slice(cardIndex)};render()}
function validTableau(card,target){if(!target)return card.rank===13;return target.up&&suits[card.suit].c!==suits[target.suit].c&&card.rank===target.rank-1}
function take(){if(!selected)return[];let cards;if(selected.type==='waste')cards=[waste.pop()];else if(selected.type==='foundation')cards=[foundations[selected.index].pop()];else cards=tableau[selected.index].splice(selected.cardIndex);return cards}
function reveal(ci){let c=tableau[ci]?.at(-1);if(c&&!c.up)c.up=true}
function moveToTableau(ci){if(!selected)return;let first=selected.cards[0],target=tableau[ci].at(-1);if(!validTableau(first,target))return;let from=selected.type==='tableau'?selected.index:null,cards=take();tableau[ci].push(...cards);if(from!==null)reveal(from);selected=null;moves++;render()}
function moveToFoundation(fi){if(!selected||selected.cards.length!==1)return;let c=selected.cards[0],top=foundations[fi].at(-1);if(c.suit!==fi||c.rank!==(top?top.rank+1:1))return;let from=selected.type==='tableau'?selected.index:null;foundations[fi].push(take()[0]);if(from!==null)reveal(from);selected=null;moves++;render()}
function autoFoundation(type,index,cardIndex){choose(type,index,cardIndex);if(selected?.cards.length===1)moveToFoundation(selected.cards[0].suit)}
function checkWin(){if(foundations.every(f=>f.length===13)){ $('#winMoves').textContent=`Completed in ${moves} moves.`;$('#win').hidden=false}}
$('#newDeal').onclick=newDeal;$('#restart').onclick=restart;$('#playAgain').onclick=()=>{$('#win').hidden=true;newDeal()};$('#creditsButton').onclick=()=>$('#credits').showModal();$('#credits .close').onclick=()=>$('#credits').close();
$('#creditList').innerHTML=`<p><b>Mac Miller:</b> Nicolas Völcker, CC BY-SA 4.0.</p><p><b>Tana Mongeau:</b> Tanner Fox, CC BY 3.0.</p><p><b>Flea:</b> Clare Cridland, CC BY 2.0.</p><p><b>Tiger Woods:</b> Jim Epler, CC BY 2.0.</p><p>See ATTRIBUTION.md for source links and full license details.</p>`;
newDeal();
