const suits=[{s:'♠',c:'black'},{s:'♥',c:'red'},{s:'♦',c:'red'},{s:'♣',c:'black'}],faces={1:{name:'TIGER WOODS',img:'assets/tiger-woods.jpg'},11:{name:'MAC MILLER',img:'assets/mac-miller.jpg'},12:{name:'TANA MONGEAU',img:'assets/tana-mongeau.png'},13:{name:'FLEA',img:'assets/flea-live.jpg'}};
let stock=[],waste=[],foundations=[[],[],[],[]],tableau=[[],[],[],[],[],[],[]],selected=null,moves=0,initialDeck=[];
const $=s=>document.querySelector(s),tableauEl=$('#tableau'),foundationEl=$('#foundations');
function deck(){return suits.flatMap((s,si)=>Array.from({length:13},(_,i)=>({suit:si,rank:i+1,up:false,id:`${si}-${i+1}`})))}
function shuffle(a){for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function deal(cards){stock=cards.map(c=>({...c}));waste=[];foundations=[[],[],[],[]];tableau=[[],[],[],[],[],[],[]];for(let col=0;col<7;col++)for(let row=0;row<=col;row++){let c=stock.pop();c.up=row===col;tableau[col].push(c)}selected=null;moves=0;render()}
function solvableDeck(){let roles=shuffle([0,1,2,3]),cols=[[],[],[],[],[],[],[]],add=(col,suit,high,low)=>{for(let rank=high;rank>=low;rank--)cols[col].push({suit,rank,up:false,id:`${suit}-${rank}`})};add(6,roles[0],7,1);add(2,roles[0],10,8);add(5,roles[1],6,1);add(1,roles[1],8,7);add(4,roles[2],5,1);add(0,roles[2],6,6);add(3,roles[3],4,1);let next={[roles[0]]:11,[roles[1]]:9,[roles[2]]:7,[roles[3]]:5},drawOrder=[];while(drawOrder.length<24){let available=roles.filter(s=>next[s]<=13),s=available[Math.floor(Math.random()*available.length)],rank=next[s]++;drawOrder.push({suit:s,rank,up:false,id:`${s}-${rank}`})}let dealOrder=cols.flat();return [...drawOrder.reverse(),...dealOrder.reverse()]}
function newDeal(){$('#win').hidden=true;initialDeck=solvableDeck();deal(initialDeck)}function restart(){$('#win').hidden=true;deal(initialDeck)}
function label(r){return r===1?'A':r===11?'J':r===12?'Q':r===13?'K':r}
function beginDrag(type,index,cardIndex,e){if(type==='waste')selected={type,index:0,cardIndex:waste.length-1,cards:[waste.at(-1)]};else if(type==='foundation')selected={type,index,cardIndex,cards:[foundations[index].at(-1)]};else if(type==='tableau'){let card=tableau[index][cardIndex];if(!card?.up)return e.preventDefault();selected={type,index,cardIndex,cards:tableau[index].slice(cardIndex)}}else return e.preventDefault();e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',selected.cards[0].id)}
function allowDrop(e){e.preventDefault();e.dataTransfer.dropEffect='move'}
function cardEl(c,source,index,cardIndex){let el=document.createElement('div');el.className=`card ${c.up?'':'back'} ${suits[c.suit].c==='red'?'red':''}`;el.dataset.id=c.id;if(selected?.cards?.some(x=>x.id===c.id))el.classList.add('selected');if(c.up){let f=faces[c.rank];el.innerHTML=`<span class="rank">${label(c.rank)}<br>${suits[c.suit].s}</span><span class="rank bottom">${label(c.rank)}<br>${suits[c.suit].s}</span>${f?`<img class="portrait" draggable="false" src="${f.img}" alt="${f.name}"><span class="name">${f.name}</span>`:`<span class="pip">${suits[c.suit].s}</span>`}`;el.draggable=source!=='stock';el.ondragstart=e=>beginDrag(source,index,cardIndex,e);el.ondragend=()=>{if(selected){selected=null;render()}};el.onclick=e=>{e.stopPropagation();if(selected?.cards?.some(x=>x.id===c.id)){selected=null;return render()}if(selected){if(source==='tableau')return moveToTableau(index);if(source==='foundation')return moveToFoundation(index)}choose(source,index,cardIndex)};el.ondblclick=e=>{e.stopPropagation();autoMove(source,index,cardIndex)}}return el}
function render(){tableauEl.innerHTML='';tableauEl.style.minHeight=`${Math.max(360,Math.max(...tableau.map(c=>c.length),1)*32+190)}px`;tableau.forEach((col,ci)=>{let pile=document.createElement('div');pile.className='column';pile.onclick=()=>moveToTableau(ci);pile.ondragover=allowDrop;pile.ondrop=e=>{e.preventDefault();moveToTableau(ci)};col.forEach((c,i)=>{let el=cardEl(c,'tableau',ci,i);el.style.top=`${i*32}px`;el.style.zIndex=i;pile.append(el)});tableauEl.append(pile)});let st=$('#stock');st.innerHTML='';st.dataset.label='↻';if(stock.length){let c=cardEl({...stock.at(-1),up:false},'stock',0,0);st.append(c)}st.onclick=draw;let wa=$('#waste');wa.innerHTML='';wa.dataset.label='WASTE';if(waste.length){let c=cardEl(waste.at(-1),'waste',0,waste.length-1);wa.append(c)}foundationEl.innerHTML='';foundations.forEach((f,i)=>{let p=document.createElement('div');p.className='pile';p.dataset.label=suits[i].s;p.onclick=()=>moveToFoundation(i);p.ondragover=allowDrop;p.ondrop=e=>{e.preventDefault();moveToFoundation(i)};if(f.length)p.append(cardEl(f.at(-1),'foundation',i,f.length-1));foundationEl.append(p)});$('#moves').textContent=`${moves} MOVE${moves===1?'':'S'}`;checkWin()}
function draw(){selected=null;if(stock.length){let c=stock.pop();c.up=true;waste.push(c)}else{stock=waste.reverse().map(c=>({...c,up:false}));waste=[]}moves++;render()}
function choose(type,index,cardIndex){if(type==='stock')return draw();if(type==='foundation'){selected={type,index,cardIndex,cards:[foundations[index].at(-1)]};return render()}if(type==='waste'){selected={type,index:0,cardIndex:waste.length-1,cards:[waste.at(-1)]};return render()}let col=tableau[index],card=col[cardIndex];if(!card.up)return;selected={type,index,cardIndex,cards:col.slice(cardIndex)};render()}
function validTableau(card,target){if(!target)return card.rank===13;return target.up&&suits[card.suit].c!==suits[target.suit].c&&card.rank===target.rank-1}
function take(){if(!selected)return[];let cards;if(selected.type==='waste')cards=[waste.pop()];else if(selected.type==='foundation')cards=[foundations[selected.index].pop()];else cards=tableau[selected.index].splice(selected.cardIndex);return cards}
function reveal(ci){let c=tableau[ci]?.at(-1);if(c&&!c.up)c.up=true}
function moveToTableau(ci){if(!selected)return;let first=selected.cards[0],target=tableau[ci].at(-1);if(!validTableau(first,target))return;let from=selected.type==='tableau'?selected.index:null,cards=take();tableau[ci].push(...cards);if(from!==null)reveal(from);selected=null;moves++;render()}
function moveToFoundation(fi){if(!selected||selected.cards.length!==1)return;let c=selected.cards[0],top=foundations[fi].at(-1);if(c.suit!==fi||c.rank!==(top?top.rank+1:1))return;let from=selected.type==='tableau'?selected.index:null;foundations[fi].push(take()[0]);if(from!==null)reveal(from);selected=null;moves++;render()}
function autoMove(type,index,cardIndex){choose(type,index,cardIndex);if(!selected)return;let card=selected.cards[0];if(selected.cards.length===1){let top=foundations[card.suit].at(-1);if(card.rank===(top?top.rank+1:1))return moveToFoundation(card.suit)}let destination=tableau.findIndex((col,ci)=>!(type==='tableau'&&ci===index)&&validTableau(card,col.at(-1)));if(destination>=0)return moveToTableau(destination);selected=null;render()}
function checkWin(){if(foundations.every(f=>f.length===13)){ $('#winMoves').textContent=`Completed in ${moves} moves.`;$('#win').hidden=false}}
$('#newDeal').onclick=newDeal;$('#restart').onclick=restart;$('#playAgain').onclick=()=>{$('#win').hidden=true;newDeal()};$('#creditsButton').onclick=()=>$('#credits').showModal();$('#credits .close').onclick=()=>$('#credits').close();
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&selected){selected=null;render()}});
$('#creditList').innerHTML=`<p><b>Mac Miller:</b> Nicolas Völcker, CC BY-SA 4.0.</p><p><b>Tana Mongeau:</b> Tanner Fox, CC BY 3.0.</p><p><b>Flea:</b> Clare Cridland, CC BY 2.0.</p><p><b>Tiger Woods:</b> Jim Epler, CC BY 2.0.</p><p>See ATTRIBUTION.md for source links and full license details.</p>`;
newDeal();
